site_name: Tristan Slater
site_url: https://trslater.ca
# repo_name: trslater/trslater.github.io
# repo_url: https://github.com/trslater/trslater.github.io

theme:
  name: material
  logo: assets/images/logo.svg
  custom_dir: overrides
  palette:
    scheme: slate
    primary: deep purple
    accent: teal

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/trslater/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tristanslater/

watch:
  - overrides
