site_name: Tristan Slater
site_url: https://trslater.ca

theme:
  name: material
  logo: assets/images/logo.svg
  palette:
    scheme: slate
    primary: deep purple
    accent: teal

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/trslater/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tristanslater/

markdown_extensions:
  - attr_list
